package com.tcmp.fcupload.dto.recordType;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class Details {
    private String instrumentUniqueReference;
    private String instrumentReference;
    private String paymentProduct;
    private String packageName;
    private String instrumentNumber;
    private String instrumentAmount;
    private String instrumentCurrency;
    private String debitAccount;
    private String debitReferenceNumber;
    private String debitDescription;
    private String creditReferenceNumber;
    private String creditDescription;
    private String benefName;
    private String beneficiaryBankBicCode;
    private String beneficiaryBankName;
    private String beneficiaryBankAddressLine1;
    private String beneficiaryBankAddressLine2;
    private String beneficiaryBankAddressLine3;
    private String beneficiaryBankPostalCode;
    private String beneficiaryBankCity;
    private String beneficiaryBankState;
    private String beneficiaryBankCountry;
    private String fxContractRate;
    private String fxRateType;
    private String beneficiaryAccount;
    private String beneficiaryAddressLine1;
    private String beneficiaryAddressLine2;
    private String beneficiaryAddressLine3;
    private String beneficiaryPostalCode;
    private String beneficiaryCountry;
    private String beneficiaryEmailId;
    private String beneficiaryMobileNumber;
    private String corrBankAddress1;
    private String intermediaryBankIdType;
    private String intermediaryBankCode;
    private String intermediaryBankName;
    private String intermediaryBankBic;
    private String intermediaryBankNostroAccount;
    private String intermediaryBankAddress1;
    private String intermediaryBankCity;
    private String intermediaryBankCountry;
    private String intermediaryBankDetails1;
    private String beneficiaryBankId;
    private String beneficiaryBankIdType;
    private String remittanceInfo1;
    private String remittanceInfo2;
    private String remittanceInfo3;
    private String remittanceInfo4;
    private String standingInstructionStartDate;
    private String standingInstructionEndDate;
    private String standingInstructionTypeOfDate;
    private String standingInstructionFrequency;
    private String standingInstructionPeriod;
    private String standingInstructionReferenceDay;
    private String standingInstructionHolidayAction;
    private String enrichmentValue1;
    private String enrichmentValue2;
    private String enrichmentValue3;
    private String enrichmentValue4;
    private String enrichmentValue5;
    private String enrichmentValue6;
    private String enrichmentValue7;
    private String enrichmentValue8;
    private String enrichmentValue9;
    private String enrichmentValue10;
    private String enrichmentValue11;
    private String enrichmentValue12;
    private String enrichmentValue13;
    private String enrichmentValue14;
    private String enrichmentValue15;
    private String enrichmentValue16;
    private String enrichmentValue17;
    private String enrichmentValue18;
    private String enrichmentValue19;
    private String enrichmentValue20;
    private String regulatoryReporting1;
    private String regulatoryReporting2;
    private String regulatoryReporting3;
    private String regulatoryReporting4;
    private String regulatoryReporting5;
}
