spring:
  activemq:
    host: ${MQ_HOST}
    port: ${MQ_PORT}
    user: ${MQ_USER}
    password:  ${MQ_PASSWORD}
    broker-url: "tcp://${spring.activemq.host}:${spring.activemq.port}"
    packages:
      trust-all: true
debts:
  static:
    cif: ${TEST_CIF}
  datasource:
    host: ${DB_HOST}
    port: ${DB_PORT}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    server-name: ${DB_SEVER}
    url: jdbc:oracle:thin:@//${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.server-name}
  jpa:
    database-platform: "org.hibernate.dialect.Oracle12cDialect"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.Oracle12cDialect"  